---
- hosts: all
  sudo: True
  tasks:
  
    - name: update hostname
      hostname: name=kabuto
  
    - name: install deps
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - python3
        - python3-dev
        - libffi-dev
        - rabbitmq-server
        - python3-pip
  
    - name: install docker
      shell: wget -qO- https://get.docker.com/ | sh
      
    - name: add user in docker group
      user: name={{ansible_ssh_user}} groups=docker append=yes
      
    - name: install pip deps
      command: pip3 install -r /vagrant/requirements.txt
      
    - name: run docker registry
      command: docker run -d -p 7900:5000 registry